version: '3.8'

# Development version with local builds
# Use: docker compose -f docker-compose.dev.yml up -d

services:
  bluesky-bot:
    build: .
    restart: unless-stopped
    environment:
      # Feedmaster API
      FEEDMASTER_API_URL: ${FEEDMASTER_API_URL:-https://feedmaster.fema.monster}
      FEED_IDS: ${FEED_IDS}
      
      # Bluesky credentials
      BLUESKY_USERNAME: ${BLUESKY_USERNAME}
      BLUESKY_DID: ${BLUESKY_DID}
      BLUESKY_APP_PASSWORD: ${BLUESKY_APP_PASSWORD}
      
      # Bot settings
      MIN_RARITY_TIER: ${MIN_RARITY_TIER:-Diamond}
      POLL_INTERVAL_MINUTES: ${POLL_INTERVAL_MINUTES:-10}
      MAX_POSTS_PER_HOUR: ${MAX_POSTS_PER_HOUR:-30}
      MESSAGE_TEMPLATE: ${MESSAGE_TEMPLATE:-🎉 Congratulations @{username} on earning "{achievement}"! Only {percentage}% of users have achieved this {rarity} rarity! Track your achievements at feedmaster.fema.monster}
    volumes:
      - ./logs:/app/logs
      - ./bot.py:/app/bot.py  # Mount source code for live updates
      - ./config_server.py:/app/config_server.py
  
  config-server:
    build: .
    command: python config_server.py
    ports:
      - "8080:8080"
    volumes:
      - ./.env:/app/.env
      - /var/run/docker.sock:/var/run/docker.sock
      - ./bot.py:/app/bot.py  # Mount source code for live updates
      - ./config_server.py:/app/config_server.py
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
      - CONFIG_USERNAME=${CONFIG_USERNAME:-admin}
      - CONFIG_PASSWORD=${CONFIG_PASSWORD:-changeme}