version: '3.8'

services:
  bluesky-bot:
    build: .
    restart: unless-stopped
    environment:
      # Feedmaster API
      FEEDMASTER_API_URL: ${FEEDMASTER_API_URL:-https://feedmaster.fema.monster}
      FEED_IDS: ${FEED_IDS}
      
      # Bluesky credentials
      BLUESKY_USERNAME: ${BLUESKY_USERNAME}
      BLUESKY_APP_PASSWORD: ${BLUESKY_APP_PASSWORD}
      
      # Bot settings
      MIN_RARITY_TIER: ${MIN_RARITY_TIER:-Diamond}
      POLL_INTERVAL_MINUTES: ${POLL_INTERVAL_MINUTES:-5}
      MAX_POSTS_PER_HOUR: ${MAX_POSTS_PER_HOUR:-10}
      MESSAGE_TEMPLATE: ${MESSAGE_TEMPLATE:-🎉 Congratulations @{username} on earning "{achievement}"! Only {percentage}% of users have achieved this {rarity} rarity! Track your achievements at feedmaster.fema.monster}
    volumes:
      - ./logs:/app/logs